# -*- coding: utf-8 -*-
"""api_research

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LVfrDiAl61HDTtAQiGbEH0zNTM0Mm32
"""

# Install official SDK
!pip install openfoodfacts

from openfoodfacts import ProductDataset
import pandas as pd

# Download and auto-cache the CSV dataset (~2GB)
dataset = ProductDataset(dataset_type="csv")

# Extract key columns for WiseWhisk
foods = []
for product in dataset:
    if product.get('product_name'):  # Only items with names
        foods.append({
            'name': product.get('product_name', ''),
            'calories': product.get('energy_kcal_100g', ''),
            'fat': product.get('fat_100g', ''),
            'sugar': product.get('sugars_100g', ''),
            'protein': product.get('proteins_100g', ''),
            'sodium': product.get('salt_100g', ''),
            'allergens': product.get('allergens_tags', ''),
            'additives': product.get('additives_tags', ''),
            'nutri_score': product.get('nutriscore_grade', ''),
            'category': product.get('categories_tags', '')
        })

# Save to CSV
df = pd.DataFrame(foods)
df.to_csv('wisewhisk_foods_10k.csv', index=False)
print(f"Extracted {len(df)} products with nutrition data")